In [1]:
import numpy as np
import keras as k
import rules
import arena as arn
from bot_base import BOT


bot_rd = arn.bot_rd
bot_me = arn.bot_me


In [6]:
model_0 = k.models.load_model("model_base/m2506.keras")
model = k.models.load_model("model_base/m3528.keras")

In [8]:
def bot_mc_f(basebot, verbos=2, RECORD=True, MAXWIDTH=3, NSIMS_FACTOR=50, NSIMS_MAX=1000):
    return mc.BOT(basebot=basebot, verbos=verbos, RECORD=RECORD, MAXWIDTH=MAXWIDTH, NSIMS_FACTOR=NSIMS_FACTOR, NSIMS_MAX=NSIMS_MAX)

In [7]:
def ft(N, ARENA):
    s1, s2 = 0, 0
    for i in range(N):
        cards = rules.CARDS.copy()
        np.random.shuffle(cards)
        
        arena = ARENA(verbos=0, cards=cards.copy())
        arena.registerbot([BOT(model), BOT(model_0), BOT(model_0)])
        # arena.registerbot([BOT(model), bot_rd, bot_rd])
        arena.wholegame()
        s1 += (arena.winner == 0)
        
        arena2 = ARENA(verbos=0, cards=cards.copy())
        arena2.registerbot([BOT(model_0), BOT(model), BOT(model)])
        arena2.wholegame()
        s2 += (arena2.winner == 0)
        
    # for i in range(N):
    #     arena = ARENA(verbos=0)
    #     arena.registerbot([BOT(model_0), BOT(model), BOT(model)])
    #     # arena.registerbot([BOT(model_0), bot_rd, bot_rd])
    #     arena.wholegame()
    #     s2 += (arena.winner == 0)
    return s1, s2

In [8]:
ft(1000, arn.ARENA)

(578, 506)

In [6]:
import re

def repl(matched):
    d = {"11": "J", "12": "Q", "13": "K", "14": "A", "15": "2", "16": "小王", "17": "大王"}
    return d[matched[0]]

def arenabyscratch(l):
    cards = [rules.str2vec(re.sub(r'1[1-7]', repl, v)) for v in re.split(",", l)]
        
    arena=object.__new__(arn.ARENA)
    arena.verbos = 1
    arena.init = np.array(cards, int)
    arena.remain = arena.init.copy()
    arena.lastplay = np.zeros((3, 15), int)
    arena.pos = 0
    arena.b1 = 2
    arena.b2 = 1
    arena.round = 0
    arena.bot = []
    arena.gameover = False
    arena.winner = None
    arena.getdata()
    arena.RECORD = True
    arena.records = []
    if arena.RECORD:
        arena.records.append(arena.copy())
    return arena

arena = arenabyscratch("3 4 4 4 4 5 5 7 8 9 9 9 10 11 12 13 13 14 14 17, 3 5 5 6 6 6 7 7 7 8 9 10 11 12 13 13 15, 3 3 6 8 8 10 10 11 11 12 12 14 14 15 15 15 16")

In [75]:
# %%time
# bot_hyb = hyb.BOT(bot, bot, verbos=1, NINFER=10, tao=0.04)
arena = arn.ARENA(1, True)
arena.registerbot([BOT(model,verbos=1), BOT(model,verbos=1), BOT(model,verbos=1)])
# arena.registerbot([BOT(model,verbos=1), bot_rd, bot_rd])
arena.wholegame()

0.302651 3 4 5 6 7 8 9 10
0.24438982 3 4 5 6 7 8 9 10 J
0.19220126 3 4 5 6 7 8 9
0.19081652 3 4 5 6 7
0.17986386 6 7 8 9 10
 0 :  地主 : 3 4 5 6 7 8 9 10 | 4 5 8 8 J J Q Q Q K K A
0.7406875 
 1 : 农民1 :  | 3 4 5 6 6 6 7 9 9 10 J K A A 2 2 小王
0.7454597 7 8 9 10 J Q K A
0.5852662 
 2 : 农民2 : 7 8 9 10 J Q K A | 3 3 4 5 7 10 2 2 大王
0.23931284 
 3 :  地主 :  | 4 5 8 8 J J Q Q Q K K A
0.7660098 
 4 : 农民1 :  | 3 4 5 6 6 6 7 9 9 10 J K A A 2 2 小王
0.63232 4
0.62432134 3 3
0.6179281 5
0.616632 10
0.595998 7
 5 : 农民2 : 4 | 3 3 5 7 10 2 2 大王
0.3883019 5
0.26352745 A
0.19284718 8
0.16853915 
0.16644634 J
 6 :  地主 : 5 | 4 8 8 J J Q Q Q K K A
0.71169347 2
0.70020175 K
0.69356596 9
0.6923727 J
0.68609464 
 7 : 农民1 : 2 | 3 4 5 6 6 6 7 9 9 10 J K A A 2 小王
0.55403304 
0.5465089 大王
 8 : 农民2 :  | 3 3 5 7 10 2 2 大王
0.42027193 
 9 :  地主 :  | 4 8 8 J J Q Q Q K K A
0.6818818 K
0.6812321 2
0.6754614 9
0.67542493 J
0.6744392 3
10 : 农民1 : K | 3 4 5 6 6 6 7 9 9 10 J A A 2 小王
0.5498892 2
0.47104853 
0.45677418 大王
11 : 农

In [67]:
tmp = arena.records[31]

In [70]:
BOT.getdata(tmp)[0,2]

array([[1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
a1 = arena.records[0].copy(0, True)
a1.registerbot([bot, bot, bot])

In [11]:
a1.pos

0

In [12]:
a1.remain

array([[2, 2, 1, 4, 3, 1, 0, 2, 1, 1, 0, 1, 2, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 2, 3, 1, 0, 1],
       [1, 1, 2, 0, 1, 2, 3, 1, 1, 1, 2, 0, 1, 1, 0]])

In [13]:
a1.lastplay

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [72]:
bot.showChoices(a1)

AttributeError: 'BOT' object has no attribute 'arena'

In [15]:
a1 = arena.records[0].copy(0, True)

In [18]:
a1.update(a1.getChoices()[0])

In [73]:
bot.eval(a1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.3892856538295746>

In [33]:
data = bot.getdata(a1)

In [58]:
bot.model.predict(data, verbose = 0)[0, 0]

np.float32(0.38928565)

In [76]:
bot.model(data)[0,0].numpy()

np.float32(0.38928565)

In [38]:
%%timeit
bot.model.predict(data, verbose = 0)

94.9 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%%timeit
bot.model(data)

11.9 ms ± 654 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%%timeit
bot.model(data, training = False)

13 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
%%timeit
bot.model(data)[0,0].numpy()

11.6 ms ± 553 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
