In [70]:
import numpy as np
import keras as k
import rules
import arena as arn
import bot_nn as nn

bot_rd = arn.bot_rd
bot_me = arn.bot_me
import importlib
importlib.reload(nn)

<module 'bot_nn' from 'd:\\py\\ddz_2025_2\\bot_nn.py'>

In [71]:
model = nn.BOT.createmodel()
model.load_weights("weights/weights/w{0}.weights.h5".format(135))
bot = nn.BOT(model, verbos=1)

In [8]:
def bot_mc_f(basebot, verbos=2, RECORD=True, MAXWIDTH=3, NSIMS_FACTOR=50, NSIMS_MAX=1000):
    return mc.BOT(basebot=basebot, verbos=verbos, RECORD=RECORD, MAXWIDTH=MAXWIDTH, NSIMS_FACTOR=NSIMS_FACTOR, NSIMS_MAX=NSIMS_MAX)

In [9]:
def ft(N, ARENA, BOT_T, BOT_B):
    s1, s2 = 0, 0
    for i in range(N):
        arena = ARENA(verbos=0)
        arena.registerbot([BOT_T(), BOT_B(), BOT_B()])
        arena.wholegame()
        s1 += (arena.winner == 0)
    for i in range(N):
        arena = ARENA(verbos=0)
        arena.registerbot([BOT_B(), BOT_T(), BOT_T()])
        arena.wholegame()
        s2 += (arena.winner != 0)
    return (s1, s2)

In [14]:
%%time
ft(100, arn.ARENA, lambda: bot_im, lambda: bot_rd)

Wall time: 28.4 s


(47, 84)

In [6]:
import re

def repl(matched):
    d = {"11": "J", "12": "Q", "13": "K", "14": "A", "15": "2", "16": "小王", "17": "大王"}
    return d[matched[0]]

def arenabyscratch(l):
    cards = [rules.str2vec(re.sub(r'1[1-7]', repl, v)) for v in re.split(",", l)]
        
    arena=object.__new__(arn.ARENA)
    arena.verbos = 1
    arena.init = np.array(cards, int)
    arena.remain = arena.init.copy()
    arena.lastplay = np.zeros((3, 15), int)
    arena.pos = 0
    arena.b1 = 2
    arena.b2 = 1
    arena.round = 0
    arena.bot = []
    arena.gameover = False
    arena.winner = None
    arena.getdata()
    arena.RECORD = True
    arena.records = []
    if arena.RECORD:
        arena.records.append(arena.copy())
    return arena

arena = arenabyscratch("3 4 4 4 4 5 5 7 8 9 9 9 10 11 12 13 13 14 14 17, 3 5 5 6 6 6 7 7 7 8 9 10 11 12 13 13 15, 3 3 6 8 8 10 10 11 11 12 12 14 14 15 15 15 16")

In [74]:
%%time
# bot_hyb = hyb.BOT(bot, bot, verbos=1, NINFER=10, tao=0.04)
arena = arn.ARENA(1, True)
arena.registerbot([bot, bot, bot])
arena.wholegame()

tf.Tensor(0.48331225, shape=(), dtype=float32) 4 8 8 8 9 9 9 10
tf.Tensor(0.47581518, shape=(), dtype=float32) 3 4 8 8 8 9 9 9
tf.Tensor(0.47237837, shape=(), dtype=float32) 3 3 8 8 8 9 9 9
tf.Tensor(0.47177172, shape=(), dtype=float32) 3 3 6 6 6
tf.Tensor(0.4713077, shape=(), dtype=float32) 4 6 6 6
 0 :  地主 : 4 8 8 8 9 9 9 10 | 3 3 6 6 6 Q K K K A 2 2
0.5470381 
 1 : 农民1 :  | 3 3 4 4 5 6 7 7 9 10 J Q Q Q K A 2
0.44082612 
0.43445563 小王 大王
 2 : 农民2 :  | 4 5 5 5 7 7 8 10 10 J J J A A 2 小王 大王
tf.Tensor(0.52299905, shape=(), dtype=float32) 3 3 6 6 6
tf.Tensor(0.5121164, shape=(), dtype=float32) 3 3
tf.Tensor(0.5085356, shape=(), dtype=float32) 3 3 K K K
tf.Tensor(0.49186784, shape=(), dtype=float32) 6 6 6 A
tf.Tensor(0.49126682, shape=(), dtype=float32) 3 6 6 6
 3 :  地主 : 3 3 6 6 6 | Q K K K A 2 2
0.4934736 7 7 Q Q Q
0.4914512 4 4 Q Q Q
0.48159593 3 3 Q Q Q
0.4763177 
 4 : 农民1 : 7 7 Q Q Q | 3 3 4 4 5 6 9 10 J K A 2
0.43699318 
0.42276978 小王 大王
 5 : 农民2 :  | 4 5 5 5 7 7 8 10 10 J J J A A 2

In [10]:
a1 = arena.records[0].copy(0, True)
a1.registerbot([bot, bot, bot])

In [11]:
a1.pos

0

In [12]:
a1.remain

array([[2, 2, 1, 4, 3, 1, 0, 2, 1, 1, 0, 1, 2, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 2, 3, 1, 0, 1],
       [1, 1, 2, 0, 1, 2, 3, 1, 1, 1, 2, 0, 1, 1, 0]])

In [13]:
a1.lastplay

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [72]:
bot.showChoices(a1)

AttributeError: 'BOT' object has no attribute 'arena'

In [15]:
a1 = arena.records[0].copy(0, True)

In [18]:
a1.update(a1.getChoices()[0])

In [73]:
bot.eval(a1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.3892856538295746>

In [33]:
data = bot.getdata(a1)

In [58]:
bot.model.predict(data, verbose = 0)[0, 0]

np.float32(0.38928565)

In [76]:
bot.model(data)[0,0].numpy()

np.float32(0.38928565)

In [38]:
%%timeit
bot.model.predict(data, verbose = 0)

94.9 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%%timeit
bot.model(data)

11.9 ms ± 654 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%%timeit
bot.model(data, training = False)

13 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
%%timeit
bot.model(data)[0,0].numpy()

11.6 ms ± 553 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
